### ISSUE TITLE
Text Size

### ISSUE THREAD

**Issue by Ashe-H** [xorus/EngageTimer#12]
Hello, 
First of all thank you for making this plugins it help a lot when it comes to not early pulling :)

I was wondering if there's a possibility of resizing the text and drag it around and if not is it something that can be considered in the futur ? 

Regards

**Comment by xorus** [comment]
Hi, if I understand correctly, you mean to resize and move the big countdown thing, right?

**Comment by Ashe-H** [comment]
Exactly.

**Comment by Ashe-H** [comment]
Cool, thank you so much :)
