### ISSUE TITLE
CD overlay can overlap with the in-game one when starting&cancelling

### ISSUE THREAD

**Issue by xorus** [xorus/EngageTimer#19]
From discord (Kanaris)

> Oh btw @Xorus this was an issue from long before EW, but i never got around to making an issue ticket for it.
The engage timer countdown bugs out and overlaps with the vanilla game one if you start and cancel a countdown, or if you wipe during a countdown (from someone messing up prepull, for example). Actually I can't remember which of these it is, or if it is both, but it's worth looking into both of them. It came up many a time during TEA prog.
oh to clarify, it overlaps on the next countdown, after the one where you cancelled or wiped

**Comment by xorus** [comment]
this one is really not easy to fix :(

**Comment by cole-h** [comment]
I dunno if it helps at all, but I was able to reproduce this fairly consistently:

1. Start a countdown (any number of valid seconds), e.g. `/cd 5`
2. Cancel the countdown once it is below 5 seconds (e.g. when the game would do the 5, 4, ... countdown)
3. Start a countdown _longer_ than 5 seconds, e.g. `/cd 6`
4. See the overlapping countdowns

The countdowns will overlap until a countdown goes un-cancelled, and then the next countdown will not have any overlapping text (unless it is cancelled again below 5 seconds).

**Comment by xorus** [comment]
@cole-h thanks for the detailed steps ! 
I'll check these steps to reproduce and hopefully fix the issue soon, after I'm done with COVID.

**Comment by xorus** [comment]
Thanks for the help ! The issue should be fixed and going up on the plugin repository soon! (the update should already be available in my test repo)

**Comment by cole-h** [comment]
Woohoo! Thanks, and hope you're recovering well!
