### ISSUE TITLE
When showing decimals, countdown timer is 1 second behind

### ISSUE THREAD

**Issue by Kanarisky** [xorus/EngageTimer#2]
When the setting "Display <number> decimals in countdown" is enabled, the Ones column of the countdown value should be reduced by 1 to account for this.

Example:
https://user-images.githubusercontent.com/68185248/133959967-41dec332-b294-4192-8921-00a3a2c61b90.mp4

When the countdown usually ticks and shows "5", it is now showing "5.0", then "5.9", "5.8", all the way until "5.1", then it ticks down to show "4.0", then "4.9". If you take the point in time where it's showing "4.9", the countdown is actually at 3.9 seconds... Because 0.1 seconds after the 4 shows up is 3.9 seconds, not 4.9 seconds.

To account for this, the when the vanilla game countdown hits 5, the countdown timer should instead display 4, and then the current decimals that are already in place in the current version. All that is needed is to decrement the big number (ones column) by 1.

**Comment by Kanarisky** [comment]
Here's a bonus video comparing an accurate countdown timer to EngageTimer's decimal timer, just to demonstrate exactly what the issue is:

https://user-images.githubusercontent.com/68185248/133960457-8c16b7ee-7923-428f-a6da-f31071848108.mp4

**Comment by xorus** [comment]
Hi! This is normal when showing the original countdown and something I had to work around in the code. It's a bit confusing but in order to enable real counting you must tick the option that hides the original timer.
https://github.com/xorus/EngageTimer/blob/f1e833b2968e425f66f5b45eb6cc8d900774d7ce/Ui/CountDown.cs#L110-L118

I do not know how to handle this when showing the original countdown as it would go 7 - 6 - 5 - 5 - 4 - 3...

**Comment by Kanarisky** [comment]
Oh wow hiding the original countdown does work, you're right. Thanks for that!

I don't think it's possible to show the original countdown and have the decimals make sense, since the original countdown will always be off by 1 second when considering a decimal approach. Unless there's a way for you to play the original countdown one second early. Seeing "START .9" "START .8" etc. down to "START .1" would be weird but that's the only thing i can think of :D

**Comment by xorus** [comment]
Yep, the original countdown kinda sucks. 
Maybe I should make this more clear in the settings UI but I have no ideas how, I feel like the configuration page is getting convoluted. If you have any ideas about that, I take them.

Things I considered though :

- Adding +1 to the countdown stopwatch when using the original countdown so it matches
- Forcing the hide option when using decimals (but I don't like forcing things)
- Have a specific "original" versus "accurate" counting setting

**Comment by xorus** [comment]
I just added a setting that clarifies this so its stop being auto-magic and people can toggle it manually.
It will only be available for the next version of Dalamud which is currently is testing though.

![image](https://user-images.githubusercontent.com/2473314/135322079-2b749264-9ad1-4669-ab7a-b432a5a091bb.png)

(edit: commented the wrong screenshot)
