### ISSUE TITLE
Plugin Disabled: Crashes

### ISSUE THREAD

**Issue by ScarVite** [xorus/EngageTimer#28]
![ffxiv_dx11_az5fvQB0ND](https://user-images.githubusercontent.com/43887376/153711317-90d6bd79-2296-436b-a7c6-61139443c4f1.png)

**Comment by xorus** [comment]
I know, I fixed it this morning and still waiting on dalamud staff to accept it.
https://github.com/goatcorp/DalamudPlugins/pull/2026
