### ISSUE TITLE
[Improvement] Option to only show stopwatch inside instances

### ISSUE THREAD

**Issue by GunB** [xorus/EngageTimer#3]
Option to only show stopwatch inside instances as this option is particularly great for planned fights

**Comment by xorus** [comment]
Currently, there is an option to hide the stopwatch after X amount of time passed after the last combat to reduce screen clutter.
Or do you just want to not show up when you are pulling trash/hunts/fates in the overworld ? (I'm not sure if I can detect that yet, I need to into it).

If I did not understand, can you please add some details :) ?

**Comment by GunB** [comment]
You got it yes. I don't want to see the timer when I'm in the overworld doing hunts or collecting hides for mats or anything. I want it to show up only inside instances. Thank you for reading my request!

**Comment by xorus** [comment]
I added the thing! You'll be able to test it out when I finish this release and publish it.
Although it will only be available for the new Dalamud version that is still in testing, as this comes alongside a pretty big configuration refactor : 

![image](https://user-images.githubusercontent.com/2473314/135321670-c8ffebc3-b36b-4c35-87ee-fcaefaf978a3.png)
