### ISSUE TITLE
Closes the game after a certain time

### ISSUE THREAD

**Issue by Frousties** [xorus/EngageTimer#31]
Hello,

Since the update, whenever a timer is started, it closes my game without throwing any error message after around 5-8s (nothing either in dalamud.log).
I tried various settings, resetting them and even launching a fresh dalamud install with only this plugin installed, and nothing seems to fix this :(

Any idea what might be causing it?

**Comment by xorus** [comment]
Hmm, I guess you tried to reset the plugin's configuration ? It's a very weird issue.
Does it always happen? Could it be linked to a particular zone? 
Just in case, try to set your dalamud font to AXIS in /xlsettings too (if you use the floating window)

**Comment by Frousties** [comment]
No specific zone, it happens consistently and I am already using the AXIS font. Also tried turning floating window on / off.

**Comment by xorus** [comment]
Are you running windows ?

**Comment by Frousties** [comment]
Linux, I can try Windows too if you want.

**Comment by xorus** [comment]
Ah yes, I never tested it on linux, it might be the audio lib. Hang on

**Comment by xorus** [comment]
make sure you disabled 
![image](https://user-images.githubusercontent.com/2473314/165633604-c97d9545-d1a6-4e2c-b956-8594b6e1c5ec.png)
in the settings (`EnableTickingSound` to `false` in the JSON) while I take a dive in the code ^^

**Comment by Frousties** [comment]
Yup, that's it x)
I must've enabled it like an idiot during my tests and missed it, sorry for the needless head scratching x)

**Comment by xorus** [comment]
It's okay! Thanks for accidentally doing the test I never could :D.

I need to do some research so I can remove this ugly audio workaround by using the game.

**Comment by xorus** [comment]
I just published on my third party/testing repo (https://xorus.dev/xiv/) an update that fixes the underlying issue.

It should work no problems, but I'd appreciate it if you could test it on linux by enabling the sound option :).

The options should look like: 
![image](https://user-images.githubusercontent.com/2473314/165648077-962087cf-c6ff-4988-8167-6c95eb404d48.png)

**Comment by Frousties** [comment]
Can confirm this works!

**Comment by xorus** [comment]
Awesome! I'll publish that to the main repo sometime this week :D. Thanks for the help and brining that up!

**Comment by Frousties** [comment]
And thanks for your quick work and response ^^

**Comment by xorus** [comment]
I forgot to tell you! The update fixing the got pullished to the main repo a few days ago. If you were still using my custom/beta repository I would suggest disabling it and downloading the update from the official repo. Otherwise just be mindful that you will get beta / might-crash versions of the plugin as I add new features or test fixes for other people.
