### ISSUE TITLE
Can not enable decimals without enabling big countdown

### ISSUE THREAD

**Issue by BoredDan** [xorus/EngageTimer#44]
Right now Enable big countdown acts as the Enable button for all countdown drawing features. This means it's not possible to simply enable the decimals/accurate countdown or change the number style without adding numbers before 5. Would be beneficial to allow us to enable other feature without requiring the full countdown to be shown. Even better would be to add a custom point to start displaying the countdown timer. This would allow for players to set up the timer based on what's useful for their classes pre-pull.

**Comment by xorus** [comment]
If I understand correctly, you would just want to show the big countdown only when X seconds are left.

Tell me if this scenario would be what you are describing, imagining I add this setting, and you set it to "7" :
"Hide countdown above [ 7 ] seconds"

- Someone would start a 16s contdown (for example)
- Nothing would be shown for a while
- At 7, the 7 big number pops up, and all the numbers are drawn until the combat start

Did I understand you correctly ?

**Comment by xorus** [comment]
Yeah I got a bit confused. 
I will be implementing that then ! 

I'll definitely try to do it as soon as possible, but as a warning, I got very burnt out from the game recently so I can't promise when I will be able to do it ^^".

**Comment by xorus** [comment]
@BoredDan done! 
Can you confirm this behaviour is what you expect ?

https://user-images.githubusercontent.com/2473314/216443112-0cbb1a81-bdc5-44c1-aabf-e88978e3772c.mp4
