### ISSUE TITLE
chinese server

### ISSUE THREAD

**Issue by yuwuhuo** [xorus/EngageTimer#47]
Dear Xorus,

Greetings! I am Yuwuhuo, one of your plugin's users from China. I wanted to reach out and express our deep appreciation for the exceptional plugin you have developed. We truly admire the quality of your work.

I have noticed that the Crowdin platform for your plugin still lacks a Chinese translation submission. Therefore, I took it upon myself to personally undertake the task of translating the plugin into Chinese. I am writing this message to request permission to submit the translated "rex" files.

Please bear in mind that the English content in this message was generated using Google Translate, and there might be some unintentional offense or linguistic inaccuracies. I apologize in advance for any inconveniences caused.

My intention is to provide a more convenient and helpful experience for Chinese users through this localization effort. Your plugin has already brought tremendous convenience to our community, and I hope that my contribution through this Chinese translation can serve as a way to give back for all your hard work.

Thank you for taking the time to read this private message. I eagerly await your positive response. Once again, thank you for creating such an outstanding plugin!

Best regards,

Yuwuhuo

**Comment by xorus** [comment]
Hi! Thank you for doing this, this is very kind! I have enabled the chinese language on the Crowdin platform, now you should be able to contribute it on there. If you did it in visual studio or manually you can send me the modified resx file and I will add it to the plugin.

**Comment by xorus** [comment]
closing as the patch is now merged
https://github.com/ottercorp/DalamudPluginsD17/pull/114
