### ISSUE TITLE
engage timer overlay fontsize

### ISSUE THREAD

**Issue by schikan** [xorus/EngageTimer#50]
hello, is there a way to increase the timers fontsize ?
![timer](https://github.com/xorus/EngageTimer/assets/142495811/46a10776-e68c-4982-9892-dd3c0a82a205)

**Comment by xorus** [comment]
@schikan yes, in the settings window you can change either the text scale or the font size. It's in the "styling" sub-menu in the "floating window tab"
![image](https://github.com/xorus/EngageTimer/assets/2473314/65f39612-a9da-4fca-9cf5-5d58bcd73347)

have a nice one!

**Comment by schikan** [comment]
oh man, havent seen the options cause i didnt expand the sub menu -.- thanks alot !
