### ISSUE TITLE
option for different ticks on timer?

### ISSUE THREAD

**Issue by mogmamittens** [xorus/EngageTimer#52]
hi! I was wondering if there was a way to make it so (or if you could add the option to) you can set the countdown tick sfx (that in vanilla starts at 5) to be at a specific time on the countdown. it seems like there's only an option for the entire countdown or vanilla but I would love to be able to start it at 10s (even when the countdown is longer). thanks! :)

**Comment by xorus** [comment]
Oh that's an interesting idea!
Just some technical background as I had misread your post at first. I have absolutely no control on the ticks 1-5 as they are managed by the game (couldnt find the trickery for bypassing that yet), I actually force play the sound for the 6+ ticks :D. 
So I would not be able to make it so it only ticks for 0-3 for example but 0-10 or any amount above 5 is absolutely doable and could be very useful too!

To clarify what I have in mind for this :
- add an option in the countdown settings near the sound options "start ticking at [X]" with the field going from 5 to 30 and being disabled by default to play all ticks.
- if you set it to 10 and start a 15s timer, you'll hear ticks 10 to 1.

Thanks for the suggestion, I really want to implement it. I cannot promise you any timeframe for that though as I am still recovering from my last ffxiv burnout ^^".

**Comment by mogmamittens** [comment]
LOL totally reasonable! Sorry for the unclear wording, I really wasn't sure how to word what I was trying to describe but it seems like you got it :p That's perfect though! Definitely look forward to it even if it takes a minute :D

**Comment by xorus** [comment]
Implemented it while updating the plugin for the new Dalamud version!
