### ISSUE TITLE
Floating Window / Combat Timer Black Box 

### ISSUE THREAD

**Issue by clumsymage** [xorus/EngageTimer#65]
Hey, I recently got this plugin and love it, someone helped me with getting it and I have 1 issue.

My in combat timer has a black box around it, but the person who helped me does not. Am I missing something or?
![jXxYQsZ](https://github.com/xorus/EngageTimer/assets/169372920/b562dce0-55d1-4a2d-8f12-75b8a61aa84b)
![1AICPWI](https://github.com/xorus/EngageTimer/assets/169372920/baa0a534-23fc-42fc-aa97-44cf10ebdd5f)

**Comment by xorus** [comment]
I've never seen that either! If you are using a custom dalamud theme, try disabling / using a default one in the dalamud settings.
If that was the problem, send me the theme so I can try to fix it. 
Otherwise, check if you have multi monitor windows enabled in the dalamud settings and try disabling it, it seems unlikely but it could be that.

**Comment by clumsymage** [comment]
> I've never seen that either! If you are using a custom dalamud theme, try disabling / using a default one in the dalamud settings. If that was the problem, send me the theme so I can try to fix it. Otherwise, check if you have multi monitor windows enabled in the dalamud settings and try disabling it, it seems unlikely but it could be that.

Im using material ui with the dalamund style, ill try to disable and see what happens

**Comment by clumsymage** [comment]
Actually no clue how to change this, i disabled the plugins and i still have materialui and everything. idk im just getting mad now.. sigh, sorry

**Comment by xorus** [comment]
Don't worry about it!
I noticed sometimes dalamud plugin themes glitches out and you just have to restart. /shrug

**Comment by xorus** [comment]
Omg I'm so exhausted I misread your message entirely!! I'll download material ui tomorrow and try to figure it out

**Comment by xorus** [comment]
Disable material ui plugin, then go to dalamud settings and in the style tab change it to a default one present in the list. Then restart the game and check if the border is still there.
If you can't, ill install material ui and see if it happens whenever I get to my PC

**Comment by clumsymage** [comment]
Found it, my internet is buggin out so Im trying to test this but I keep getting kicked online and offline every few min.

**Comment by clumsymage** [comment]
Okay, it was the materialui dalamund theme, I swapped to the default one and it works now!!!! 
![Uploading zvhZ5Fv.png…]()

**Comment by clumsymage** [comment]
Okay, it was the materialui dalamund theme, I swapped to the default one and it works now!!!! 

![zvhZ5Fv](https://github.com/xorus/EngageTimer/assets/169372920/2a34bf0a-7f81-40b0-9028-097ee00720b8)

**Comment by xorus** [comment]
Alright, I'll figure out if there is something I can do to force borderless even with material ui enabled! Thanks for the info and glad the workaround works

**Comment by clumsymage** [comment]
tysm!!! sorry for the headache <3
