### ISSUE TITLE
Feature request: hide timer in cutscenes

### ISSUE THREAD

**Issue by sersorrel** [xorus/EngageTimer#68]
If I'm in a cutscene, but a party member is in combat, the combat timer appears. I'd prefer if the timer hid itself entirely during cutscenes.

(Maybe it could check for the OccupiedInCutSceneEvent condition flag? I don't know if that's the best way to do this)

I guess "hide combat timer when not bound by duty" probably accounts for most uses of this, actually...

**Comment by xorus** [comment]
Never had this case! I think I'll add a separate hide in cutscenes checkbox, thanks for the flag indication i'll look into it! (I might be a bit busy in the coming days though)
