### ISSUE TITLE
Can no longer find the Floating Window, despite resetting plugin data

### ISSUE THREAD

**Issue by Polarthief** [xorus/EngageTimer#75]
I deleted the folder, I did everything I could, but after getting a new monitor and messing with XIV settings (and then reverting them), I cannot get the floating window to appear any longer, even with a ridiculously large font size/scaling. It just, refuses to show anywhere and there's no option to "reset position" or anything.

**Comment by xorus** [comment]
That's weird, dalamud isn't supposed to let you place windows outside the screen. With xiv closed, you can reset window positions by going into the dalamud config folder and removing all EngageTimer entries from the `dalamudUI.ini` file  (.xlcore on linux/deck or appdata/Roaming/xivlauncher on windows I think ?). You can also remove the file entierly, which will reset all window positions.

**Comment by Polarthief** [comment]
Ah I forgot about the dalamudUI.ini file, thank you! Sorry, still kinda noobish to all this, I figured deleting all the other folders would work (like in pluginconfigs).
